version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile.main
    environment:
      - DATABASE=${DATABASE}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data: